# Site settings
title: RCBDev
email:
description: "A developers thoughts on all things development. Tutorials, opinions, and random posts."
baseurl: ""
url: "http://rcbdev.co.uk"
username: rcbdev
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems:
  - jekyll-sitemap
